#!/usr/bin/env python3
"""Merge user-needs markdown into a single user_needs.md at the project root.

Faithful in-container Python port of scripts/windows/merge_user_needs.ps1.
Walks requirements_user_needs/ and concatenates markdown (personas, scenarios,
user flows, plus the top-level SCENARIO_INDEX.md) into user_needs.md, prefixed
by a fixed explanatory header and an ASCII folder tree.

Excludes CHANGE_PROPAGATION.md, STATUS.md, and any file whose name starts with
"README" from the markdown collection.

Usage:
    python scripts/artifacts/merge_user_needs.py
    python scripts/artifacts/merge_user_needs.py --no-commit

Output:
    user_needs.md (project root)
"""

# tier: C  # one-shot CLI artifact generator; no in-tree Python imports

import argparse
import subprocess
import sys
from pathlib import Path

SOURCE_FOLDER = "requirements_user_needs"

# Files excluded from the markdown collection (in addition to any name
# starting with "README" — handled separately in _is_excluded).
EXCLUDED_FILES = ("CHANGE_PROPAGATION.md", "STATUS.md")

# Fixed explanatory header block. Reproduced verbatim from the PowerShell
# source (the `"..."` PS escapes become literal double quotes here, and the
# double-backtick PS escapes become literal backticks).
HEADER_LINES = [
    "# User Needs Documentation",
    "",
    "> **Note:** This file was automatically generated by `scripts/artifacts/merge_user_needs.py`.",
    "> It consolidates all user needs files from `requirements_user_needs/`.",
    "> The original files are the source of truth - this file serves as a consolidated view for easy reference.",
    "",
    "---",
    "",
    "## Understanding This Documentation",
    "",
    "This project uses a three-level user needs hierarchy to ensure features are built for actual user needs. Each level serves a distinct purpose:",
    "",
    "### 1. Personas: Psychology Over Demographics",
    "**Who** are our users - really?",
    "",
    "**WARNING - CRITICAL: Personas describe the status quo (current state WITHOUT the app).**",
    "",
    '- No "Implications for the App" or "Features This Persona Needs" sections',
    "- Describe what users do TODAY, not what the app will do for them",
    "",
    "Personas focus on psychology, not demographics:",
    "",
    "- **Mental models**: How users think the problem domain works",
    "- **Jobs to Be Done**: The progress users want to make (functional, emotional, social)",
    "- **Current Status Quo**: What tools they use TODAY and what works/doesn't work",
    "- **Trigger and Context**: When and where they engage with the problem",
    "- **Barriers**: Fears and inertia preventing change",
    "- **Anti-Traits**: What this persona is NOT (prevents scope creep)",
    "",
    "**File location:** `personas/[persona_name]/persona.md`",
    "",
    "**Evidence levels:** Use inline markers: [GREEN] grounded (interviews/data), [YELLOW] proto-persona (assumptions), [RED] hypothesis (to validate).",
    "",
    "### 2. Scenarios: Human Stories, Not Use Cases",
    "**What goals** are users trying to achieve, and in what context?",
    "",
    "**WARNING - CRITICAL: Scenarios describe the status quo (current state WITHOUT the app) by default.**",
    "",
    "- **Default approach**: Describe how users accomplish goals TODAY using current tools (paper, pen, Excel, email, notebooks)",
    "- **Purpose**: Validate real problems and pain points - not wrap hypothetical solutions in a story",
    '- **Exception**: Only scenarios explicitly marked as "Future State Scenario" may include app functionality',
    "",
    "Scenarios are goal-oriented stories using a three-act structure:",
    "",
    "- **Act 1 (Context)**: Physical state, cognitive load, the trigger (why *now*?)",
    "- **Act 2 (Interaction and Resistance)**: Obstacles, internal monologue, privacy glitches using CURRENT tools",
    '- **Act 3 (Result and Feeling)**: Emotional change, not just "data saved"',
    "",
    "Scenarios show imperfection (abandonment, interruptions), internal dialogue (doubts, fears), and privacy moments (non-user interruptions).",
    "",
    "**File location:** `personas/[persona_name]/scenarios/[scenario_name]/scenario.md`",
    "",
    '**Example:** "Brain dump at night" (status quo) - Marcus at 1:15 AM, heart racing, reaches for his paper notepad in the nightstand. He uses his phone flashlight to write, but the pen scratches loudly and his handwriting is illegible. In the morning, he can\'t read two of his three sentences - revealing the pain points of current methods (noise, data loss, illegibility).',
    "",
    "### 3. User Flows: Solution-Focused Interaction Design",
    "**How** does the app help users achieve their scenario goals?",
    "",
    "User flows are solution-oriented and specify:",
    "",
    "- **Happy path**: Main flow when everything works smoothly",
    "- **Unhappy paths**: Edge cases, user errors, system errors (local storage corruption, interruptions)",
    "- **Recovery paths**: How to get back on track after errors",
    "- **Adaptive UI**: How UI changes based on user state (e.g., mood less than 3 hides streaks)",
    "- **Environmental considerations**: Non-user presence and privacy mitigations",
    "",
    "**File location:** `personas/[persona_name]/scenarios/[scenario_name]/user_flows/[flow_name]/flow.md`",
    "",
    "**Important**: User flows involve creativity and do not always perfectly match scenarios due to technical constraints, effort trade-offs, or platform limitations. When deviations occur, they are documented with reason, impact, and mitigation.",
    "",
    "### Cross-Referencing and Bidirectional Traceability",
    "",
    "User needs and implementation are tightly connected through bidirectional references:",
    "",
    "- **User flows to Epics/Features**: User flows reference the epics and features that implement them",
    "- **Epics/Features to User flows**: Implementation files reference the user needs they serve",
    "",
    "This ensures:",
    "- Every feature serves a user need (prevents scope creep)",
    "- Every user need has implementation (prevents gaps)",
    "- Changes to user needs trigger review of related features",
    "",
    '**Deviations are expected and documented**: Implementation does not always match user needs 100% due to technical feasibility, effort constraints, or platform limitations. All deviations are documented in a "Deviations from User Needs" table showing what differs, why, the impact, and how it is mitigated.',
    "",
    "### Relationship to Implementation",
    "",
    "The connection from user needs to code:",
    "",
    "1. **Personas** inform scenarios (what users need)",
    "2. **Scenarios** describe goals and context (when/why users need it)",
    "3. **User flows** define solution approach (how the app helps)",
    "4. **Epics** (in `requirements_tasks/functional/`) implement parts of user flows",
    "5. **Features** implement specific components within epics",
    "6. **Tasks** track actual implementation work",
    "",
    "This ensures we always know **why** we are building something, **who** benefits from it, and **what constraints** we are working within.",
    "",
    "### Documentation Structure",
    "",
    "The `requirements_user_needs/` folder contains modular README files:",
    "",
    "| README | Content |",
    "|--------|---------|",
    "| README_3_PERSONA_DEFINITION | Persona template, 6 elements, checklist |",
    "| README_4_SCENARIO_DEFINITION | Scenario template, three-act structure |",
    "| README_5_USER_FLOW_DEFINITION | Flow template, exception model |",
    "| README_6_PCD_LAYER | Planet Centered Design constraints |",
    "| README_7_META_INFO_STANDARDS | YAML frontmatter, IDs, evidence markers |",
    "| README_10_WRITING_GUIDELINES | Language, tone |",
    "| README_12_REVIEW_STATUS | Review workflow |",
    "| README_15_TECHNOLOGY_NEUTRALITY | Status quo rules (Single Source of Truth) |",
    "| CHANGE_PROPAGATION | Cascade rules for modifications |",
    "",
    "---",
    "",
]


def _is_excluded(name: str) -> bool:
    """Return True if a markdown file name is excluded from the merge."""
    # Mirrors the PS filter: explicit excludes plus any name starting "README".
    return name in EXCLUDED_FILES or name.startswith("README")


def get_directory_tree(path: Path, prefix: str = "") -> list[str]:
    """Build an ASCII tree of *path*, dirs before files then by name.

    Replicates the PS Get-DirectoryTree: directories sort before files
    (Sort-Object { -not PSIsContainer }, Name), connectors "+-- "/"|-- ".
    """
    # Sort key: dirs first (False sorts before True), then name.
    items = sorted(path.iterdir(), key=lambda p: (not p.is_dir(), p.name))
    output: list[str] = []

    for i, item in enumerate(items):
        is_last = i == len(items) - 1
        connector = "+-- " if is_last else "|-- "
        extension = "    " if is_last else "|   "

        output.append(f"{prefix}{connector}{item.name}")

        if item.is_dir():
            output.extend(get_directory_tree(item, f"{prefix}{extension}"))

    return output


def collect_markdown_files(folder: Path) -> list[Path]:
    """Recursively collect non-excluded *.md files under *folder*, sorted by path."""
    if not folder.exists():
        return []
    files = [
        p
        for p in folder.rglob("*.md")
        if p.is_file() and not _is_excluded(p.name)
    ]
    # PS sorts by FullName (absolute path); sort by resolved path string.
    return sorted(files, key=lambda p: str(p))


def _append_file_section(
    content: list[str], file_path: Path, project_root: Path
) -> None:
    """Append one merged file block (separator, heading, trimmed content)."""
    relative = file_path.relative_to(project_root).as_posix()
    content.append("---")
    content.append("")
    content.append(f"#### `{relative}`")
    content.append("")
    file_content = file_path.read_text(encoding="utf-8")
    if file_content:
        # PS TrimEnd() strips trailing whitespace incl. newlines.
        content.append(file_content.rstrip())
    content.append("")
    content.append("")


def build_content(project_root: Path) -> tuple[list[str], dict[str, int]]:
    """Build the merged content lines and per-category counts."""
    folder = project_root / SOURCE_FOLDER
    content: list[str] = list(HEADER_LINES)

    # Folder Structure section.
    content.append("## Folder Structure")
    content.append("")
    if folder.exists():
        content.append("```")
        content.append(SOURCE_FOLDER)
        content.extend(get_directory_tree(folder))
        content.append("```")
        content.append("")
    content.append("---")
    content.append("")

    # SCENARIO_INDEX.md collected explicitly from the top level.
    scenario_index_path = folder / "SCENARIO_INDEX.md"
    scenario_index = scenario_index_path if scenario_index_path.exists() else None

    persona_files: list[Path] = []
    scenario_files: list[Path] = []
    flow_files: list[Path] = []

    for file_path in collect_markdown_files(folder):
        relative = file_path.relative_to(folder).as_posix()
        if _matches(relative, "user_flows/"):
            flow_files.append(file_path)
        elif _matches_scenarios(relative):
            scenario_files.append(file_path)
        elif _matches(relative, "personas/"):
            persona_files.append(file_path)

    content.append("## File Contents")
    content.append("")

    if scenario_index is not None:
        content.append("### Scenario Index")
        content.append("")
        _append_file_section(content, scenario_index, project_root)

    if persona_files:
        content.append("### Personas")
        content.append("")
        for file_path in persona_files:
            _append_file_section(content, file_path, project_root)

    if scenario_files:
        content.append("### Scenarios")
        content.append("")
        for file_path in scenario_files:
            _append_file_section(content, file_path, project_root)

    if flow_files:
        content.append("### User Flows (Shared)")
        content.append("")
        for file_path in flow_files:
            _append_file_section(content, file_path, project_root)

    counts = {
        "index": 1 if scenario_index is not None else 0,
        "personas": len(persona_files),
        "scenarios": len(scenario_files),
        "flows": len(flow_files),
    }
    return content, counts


def _matches(relative: str, top_prefix: str) -> bool:
    """Mirror PS -like "<top_prefix>*": path begins with the prefix segment."""
    return relative.startswith(top_prefix)


def _matches_scenarios(relative: str) -> bool:
    """Mirror PS -like "personas/*/scenarios/*"."""
    parts = relative.split("/")
    return (
        len(parts) > 3
        and parts[0] == "personas"
        and parts[2] == "scenarios"
    )


def commit(project_root: Path, total_files: int) -> None:
    """Stage user_needs.md and commit if it changed (mirrors PS git block)."""
    subprocess.run(
        ["git", "add", "user_needs.md"], cwd=project_root, check=True
    )
    status = subprocess.run(
        ["git", "status", "--porcelain", "user_needs.md"],
        cwd=project_root,
        check=True,
        capture_output=True,
        text=True,
    )
    if status.stdout.strip():
        message = (
            "docs: Update merged user_needs.md\n\n"
            "Generated by scripts/artifacts/merge_user_needs.py\n"
            f"Merged {total_files} markdown files from requirements_user_needs/"
        )
        subprocess.run(
            ["git", "commit", "-m", message], cwd=project_root, check=True
        )
        sys.stdout.write("Committed user_needs.md\n")
    else:
        sys.stdout.write(
            "No changes to commit (user_needs.md is up to date)\n"
        )


def main() -> int:
    """Entry point: build user_needs.md, print a summary, optionally commit."""
    parser = argparse.ArgumentParser(
        description="Merge requirements_user_needs/ markdown into user_needs.md."
    )
    parser.add_argument(
        "--no-commit",
        action="store_true",
        help="Skip the git commit (useful for testing).",
    )
    args = parser.parse_args()

    # Project root = parent of the scripts/ folder (this file is two levels deep:
    # scripts/artifacts/merge_user_needs.py).
    project_root = Path(__file__).resolve().parents[2]
    output_file = project_root / "user_needs.md"

    content, counts = build_content(project_root)

    # UTF-8 without BOM, LF line endings, joined with "\n".
    output_file.write_text("\n".join(content), encoding="utf-8", newline="\n")

    total_files = (
        counts["index"] + counts["personas"] + counts["scenarios"] + counts["flows"]
    )

    sys.stdout.write(f"Created: {output_file}\n")
    sys.stdout.write(f"Merged {total_files} markdown files.\n")
    sys.stdout.write(f"  - Scenario Index: {counts['index']}\n")
    sys.stdout.write(f"  - Personas: {counts['personas']}\n")
    sys.stdout.write(f"  - Scenarios: {counts['scenarios']}\n")
    sys.stdout.write(f"  - User Flows: {counts['flows']}\n")

    if not args.no_commit:
        commit(project_root, total_files)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
