#!/usr/bin/env python3
"""Merge requirement markdown into a single consolidated requirements.md.

Faithful Python port of scripts/windows/merge_requirements.ps1.

Walks `requirements_general_overview/` and `requirements_tasks/`, builds an
ASCII folder-structure table of contents (skipping the contents of any
`tasks/` folder except the immediate task-folder names), then concatenates
every `*.md` file outside any `tasks/` folder into `<root>/requirements.md`.

Usage:
    python3 scripts/artifacts/merge_requirements.py [--no-commit] \
        [--category {functional,non-functional,process}]

Output:
    Writes <project-root>/requirements.md (UTF-8 without BOM, LF endings).
    Prints a "Created:" line and a "Merged N markdown files." summary.
    Unless --no-commit is given, stages and commits requirements.md.

Exit codes:
    0 - success
"""

# tier: C  # one-shot CLI artifact generator; no in-tree Python imports

import argparse
import subprocess
import sys
from pathlib import Path

# Why: project root is the parent of the scripts/ dir. This file lives at
# scripts/artifacts/merge_requirements.py, so root is two levels up from
# the parent-of-parent (mirrors the PS Split-Path -Parent on the scripts dir).
SCRIPT_PATH = Path(__file__).resolve().parent  # scripts/artifacts
SCRIPTS_DIR = SCRIPT_PATH.parent  # scripts
PROJECT_ROOT = SCRIPTS_DIR.parent  # project root

FOLDERS = [
    "requirements_general_overview",
    "requirements_tasks",
]


def _sort_key(entry: Path) -> tuple[bool, str]:
    """Match the PS sort: directories before files, then by name.

    PowerShell `Sort-Object { -not $_.PSIsContainer }, Name` sorts on the
    boolean `not is_dir` first (False < True, so directories come first),
    then on the name.
    """
    return (not entry.is_dir(), entry.name)


def _list_sorted(path: Path) -> list[Path]:
    return sorted(path.iterdir(), key=_sort_key)


def get_directory_tree(
    path: Path,
    prefix: str = "",
    inside_tasks_folder: bool = False,
) -> list[str]:
    """Build an ASCII directory tree, skipping contents inside tasks folders.

    Mirrors Get-DirectoryTree: `+-- ` for the last item, `|-- ` otherwise,
    with `    ` / `|   ` continuation prefixes. A `tasks/` folder shows its
    immediate children (task names) but does not descend further.
    """
    items = _list_sorted(path)
    output: list[str] = []

    for i, item in enumerate(items):
        is_last = i == len(items) - 1
        connector = "+-- " if is_last else "|-- "
        extension = "    " if is_last else "|   "

        output.append(f"{prefix}{connector}{item.name}")

        if item.is_dir():
            is_tasks_folder = item.name == "tasks"
            skip_contents = inside_tasks_folder or is_tasks_folder

            if not skip_contents:
                output.extend(
                    get_directory_tree(item, prefix=f"{prefix}{extension}")
                )
            elif is_tasks_folder:
                # Show immediate children of tasks folder (task names) only.
                task_items = _list_sorted(item)
                for j, task_item in enumerate(task_items):
                    task_is_last = j == len(task_items) - 1
                    task_connector = "+-- " if task_is_last else "|-- "
                    output.append(
                        f"{prefix}{extension}{task_connector}{task_item.name}"
                    )

    return output


def _is_inside_tasks_folder(path: Path) -> bool:
    return "tasks" in path.parts


def get_markdown_files(
    folder_path: Path,
    category_filter: str | None = None,
) -> list[Path]:
    """Collect *.md files recursively, excluding any inside a tasks folder.

    The category filter only applies within requirements_tasks (path contains
    requirements_tasks/<category>/). Results sort by full path.
    """
    if not folder_path.exists():
        return []

    files = [
        f
        for f in folder_path.rglob("*.md")
        if not _is_inside_tasks_folder(f.relative_to(folder_path))
    ]

    if category_filter and "requirements_tasks" in folder_path.name:
        marker = f"requirements_tasks/{category_filter}/"
        files = [f for f in files if marker in f.as_posix()]

    return sorted(files, key=lambda f: str(f))


def build_content(category: str | None) -> list[str]:
    content: list[str] = []

    content.append("# Requirements Documentation")
    content.append("")
    if category:
        content.append(
            f"> **Filter Active:** Only showing **{category}** requirements"
        )
        content.append("")
    content.append(
        "> **Note:** This file was automatically generated by "
        "`scripts/artifacts/merge_requirements.py`."
    )
    content.append(
        "> It consolidates all markdown files from "
        "`requirements_general_overview/` and `requirements_tasks/`."
    )
    if category:
        content.append(f"> **Category Filter:** {category}")
    content.append(
        "> The original files are the source of truth - "
        "this file serves only as a summary."
    )
    content.append("")
    content.append("---")
    content.append("")

    content.append("## Table of Contents (Folder Structure)")
    content.append("")

    for folder in FOLDERS:
        folder_path = PROJECT_ROOT / folder
        if folder_path.exists():
            content.append(f"### {folder}/")
            content.append("")
            content.append("```")
            content.append(folder)
            content.extend(get_directory_tree(folder_path))
            content.append("```")
            content.append("")

    content.append("---")
    content.append("")

    content.append("## File Contents")
    content.append("")

    for folder in FOLDERS:
        folder_path = PROJECT_ROOT / folder
        md_files = get_markdown_files(folder_path, category)

        if md_files:
            content.append(f"### From `{folder}/`")
            content.append("")

            for file in md_files:
                relative_path = file.relative_to(PROJECT_ROOT).as_posix()

                content.append("---")
                content.append("")
                content.append(f"#### `{relative_path}`")
                content.append("")

                file_content = file.read_text(encoding="utf-8")
                if file_content:
                    content.append(file_content.rstrip())
                content.append("")
                content.append("")

    return content


def count_files(category: str | None) -> int:
    total = 0
    for folder in FOLDERS:
        total += len(get_markdown_files(PROJECT_ROOT / folder, category))
    return total


def git_commit(total_files: int) -> None:
    # Stage only the requirements.md file.
    subprocess.run(
        ["git", "add", "requirements.md"], cwd=PROJECT_ROOT, check=True
    )

    status = subprocess.run(
        ["git", "status", "--porcelain", "requirements.md"],
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout

    if status.strip():
        message = (
            "docs: Update merged requirements.md\n\n"
            "Generated by scripts/artifacts/merge_requirements.py\n"
            f"Merged {total_files} markdown files from:\n"
            "- requirements_general_overview/\n"
            "- requirements_tasks/"
        )
        subprocess.run(
            ["git", "commit", "-m", message], cwd=PROJECT_ROOT, check=True
        )
        print("Committed requirements.md")
    else:
        print("No changes to commit (requirements.md is up to date)")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Merge requirement markdown into a consolidated "
        "requirements.md file."
    )
    parser.add_argument(
        "--no-commit",
        action="store_true",
        help="Skip git commit (useful for testing).",
    )
    parser.add_argument(
        "--category",
        choices=["functional", "non-functional", "process"],
        default=None,
        help="Filter by category (only affects requirements_tasks).",
    )
    args = parser.parse_args(argv)

    output_file = PROJECT_ROOT / "requirements.md"
    content = build_content(args.category)

    # Why: write UTF-8 without BOM and LF line endings to match the PS output
    # (newline="" disables universal-newline translation so "\n".join stays LF
    # on every platform).
    output_file.write_text(
        "\n".join(content), encoding="utf-8", newline=""
    )

    print(f"Created: {output_file}")

    total_files = count_files(args.category)
    if args.category:
        print(f"Merged {total_files} markdown files (filtered: {args.category}).")
    else:
        print(f"Merged {total_files} markdown files.")

    if not args.no_commit:
        git_commit(total_files)

    return 0


if __name__ == "__main__":
    sys.exit(main())
