/// Design Token Pre-Processing Script (W3C DTCG Format)
///
/// Why: This script processes tokens.json and generates type-safe Dart classes.
/// We use manual generation instead of design_tokens_builder because:
/// 1. design_tokens_builder doesn't support runtime theme switching
/// 2. We need factor-based spacing (base × factor) which requires computation
/// 3. We have two orthogonal theme dimensions (brightness × animation mode)
/// 4. Full control over W3C DTCG format parsing and generated output
///
/// Source: requirements_tasks/.../2026-01-16_01_plan_implementation.md
///
/// Usage: dart run scripts/process_design_tokens.dart
library;

import 'dart:convert';
import 'dart:io';

void main() async {
  print('Processing design tokens (W3C DTCG format)...\n');

  try {
    // Read tokens.json
    final tokensFile = File('lib/config/theme/tokens.json');
    if (!tokensFile.existsSync()) {
      throw Exception('tokens.json not found');
    }

    final tokensJson =
        jsonDecode(await tokensFile.readAsString()) as Map<String, dynamic>;
    print('Read tokens.json');

    // Extract sections
    final primitives = tokensJson['primitives'] as Map<String, dynamic>;
    final semantic = tokensJson['semantic'] as Map<String, dynamic>?;
    final theme = tokensJson['theme'] as Map<String, dynamic>?;
    final component = tokensJson['component'] as Map<String, dynamic>?;

    // Generate tokens.g.dart
    final tokensOutput = _generateTokensFile(primitives, semantic, component);
    await File('lib/config/theme/tokens.g.dart').writeAsString(tokensOutput);
    print('Generated: lib/config/theme/tokens.g.dart');

    // Generate animation_tokens.g.dart
    if (theme != null) {
      final animationOutput = _generateAnimationTokensFile(primitives, theme);
      await File('lib/config/theme/animation_tokens.g.dart')
          .writeAsString(animationOutput);
      print('Generated: lib/config/theme/animation_tokens.g.dart');
    }

    print('\nToken generation complete!');
    print('Run "flutter test -d windows" to verify.');
  } catch (e, stackTrace) {
    print('\nError: $e');
    print('Stack trace: $stackTrace');
    exit(1);
  }
}

/// Generate main tokens.g.dart file
String _generateTokensFile(
  Map<String, dynamic> primitives,
  Map<String, dynamic>? semantic,
  Map<String, dynamic>? component,
) {
  final buffer = StringBuffer();

  // Header
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by: dart run scripts/process_design_tokens.dart');
  buffer.writeln('// Source: lib/config/theme/tokens.json (W3C DTCG format)');
  buffer.writeln('//');
  buffer.writeln('// Why: Manual generation provides full control over:');
  buffer.writeln('// - Factor-based spacing computation (base × factor)');
  buffer.writeln('// - W3C DTCG format parsing');
  buffer.writeln('// - Runtime theme switching support');
  buffer.writeln('// - Generated API design');
  buffer.writeln();
  buffer.writeln('// ignore_for_file: public_member_api_docs');
  buffer.writeln();
  buffer.writeln("import 'package:flutter/material.dart';");
  buffer.writeln();

  // Generate SpacingTokens with factor-based computation
  buffer.writeln(_generateSpacingTokens(primitives['spacing']));
  buffer.writeln();

  // Generate BorderRadiusTokens
  buffer.writeln(_generateBorderRadiusTokens(primitives['borderRadius']));
  buffer.writeln();

  // Generate FontSizeTokens
  buffer.writeln(_generateFontSizeTokens(primitives['fontSize']));
  buffer.writeln();

  // Generate ColorTokens
  buffer.writeln(_generateColorTokens(primitives['color']));
  buffer.writeln();

  // Generate SemanticColorTokens
  if (semantic != null && semantic['color'] != null) {
    buffer.writeln(_generateSemanticColorTokens(semantic['color'], primitives));
    buffer.writeln();
  }

  // Generate ComponentTokens
  if (component != null) {
    buffer.writeln(_generateComponentTokens(component, primitives));
    buffer.writeln();
  }

  // Generate BuildContext extension
  buffer.writeln(_generateContextExtension(semantic != null, component != null));

  return buffer.toString();
}

/// Generate factor-based spacing tokens
String _generateSpacingTokens(Map<String, dynamic>? spacing) {
  if (spacing == null) return '// No spacing tokens defined';

  final base = _parseValue(spacing['base']?['\$value']);
  final scale = spacing['scale'] as Map<String, dynamic>?;

  final buffer = StringBuffer();
  buffer.writeln('/// Factor-based spacing tokens.');
  buffer.writeln('/// Base unit: ${base.toStringAsFixed(0)}px');
  buffer.writeln('/// All values computed as: base × factor');
  buffer.writeln('class SpacingTokens {');
  buffer.writeln('  const SpacingTokens();');
  buffer.writeln();
  buffer.writeln('  /// Base spacing unit');
  buffer.writeln('  static const double base = $base;');
  buffer.writeln();

  if (scale != null) {
    scale.forEach((name, config) {
      if (name.startsWith('\$')) return;
      if (config is Map && config.containsKey('\$value')) {
        final factor = (config['\$value'] as num).toDouble();
        final computed = base * factor;
        final desc = config['\$description'] as String?;
        final safeName = _sanitizeName(name);

        if (desc != null) {
          buffer.writeln('  /// $desc');
        } else {
          buffer.writeln(
              '  /// ${computed.toStringAsFixed(0)}px (base × $factor)');
        }
        buffer.writeln('  static const double $safeName = $computed;');
        buffer.writeln();
      }
    });
  }

  buffer.writeln('}');
  return buffer.toString();
}

/// Generate border radius tokens
String _generateBorderRadiusTokens(Map<String, dynamic>? borderRadius) {
  if (borderRadius == null) return '// No border radius tokens defined';

  final buffer = StringBuffer();
  buffer.writeln('/// Border radius tokens.');
  buffer.writeln('class BorderRadiusTokens {');
  buffer.writeln('  const BorderRadiusTokens();');
  buffer.writeln();

  borderRadius.forEach((name, config) {
    if (name.startsWith('\$')) return;
    if (config is Map && config.containsKey('\$value')) {
      final value = _parseValue(config['\$value']);
      final desc = config['\$description'] as String?;
      final safeName = _sanitizeName(name);

      if (desc != null) buffer.writeln('  /// $desc');
      buffer.writeln('  static const double $safeName = $value;');
      buffer.writeln();
    }
  });

  buffer.writeln('}');
  return buffer.toString();
}

/// Generate font size tokens
String _generateFontSizeTokens(Map<String, dynamic>? fontSize) {
  if (fontSize == null) return '// No font size tokens defined';

  final buffer = StringBuffer();
  buffer.writeln('/// Font size tokens.');
  buffer.writeln('class FontSizeTokens {');
  buffer.writeln('  const FontSizeTokens();');
  buffer.writeln();

  fontSize.forEach((name, config) {
    if (name.startsWith('\$')) return;
    if (config is Map && config.containsKey('\$value')) {
      final value = _parseValue(config['\$value']);
      final desc = config['\$description'] as String?;
      final safeName = _sanitizeName(name);

      if (desc != null) buffer.writeln('  /// $desc');
      buffer.writeln('  static const double $safeName = $value;');
      buffer.writeln();
    }
  });

  buffer.writeln('}');
  return buffer.toString();
}

/// Generate color tokens
String _generateColorTokens(Map<String, dynamic>? color) {
  if (color == null) return '// No color tokens defined';

  final buffer = StringBuffer();
  buffer.writeln('/// Color palette tokens.');
  buffer.writeln('class ColorTokens {');
  buffer.writeln('  const ColorTokens();');
  buffer.writeln();

  // Brand colors (green palette)
  final brand = color['brand'] as Map<String, dynamic>?;
  if (brand != null && brand['green'] != null) {
    final green = brand['green'] as Map<String, dynamic>;
    buffer.writeln('  // Brand green palette');
    green.forEach((shade, config) {
      if (shade.startsWith('\$')) return;
      if (config is Map && config.containsKey('\$value')) {
        final hex = config['\$value'] as String;
        buffer.writeln('  static const Color green$shade = ${_hexToColor(hex)};');
      }
    });
    buffer.writeln();
  }

  // Fruit colors
  final fruit = color['fruit'] as Map<String, dynamic>?;
  if (fruit != null) {
    buffer.writeln('  // Fruit seed colors (for ColorScheme.fromSeed)');
    fruit.forEach((name, config) {
      if (name.startsWith('\$')) return;
      if (config is Map && config.containsKey('\$value')) {
        final hex = config['\$value'] as String;
        final desc = config['\$description'] as String?;
        final propName = 'fruit${_capitalize(name)}';

        if (desc != null) buffer.writeln('  /// $desc');
        buffer.writeln('  static const Color $propName = ${_hexToColor(hex)};');
      }
    });
    buffer.writeln();
  }

  // Neutral colors
  final neutral = color['neutral'] as Map<String, dynamic>?;
  if (neutral != null) {
    buffer.writeln('  // Neutral colors');

    // White and black
    if (neutral['white'] is Map) {
      final hex = neutral['white']['\$value'] as String;
      buffer.writeln('  static const Color white = ${_hexToColor(hex)};');
    }
    if (neutral['black'] is Map) {
      final hex = neutral['black']['\$value'] as String;
      buffer.writeln('  static const Color black = ${_hexToColor(hex)};');
    }

    // Grey palette
    final grey = neutral['grey'] as Map<String, dynamic>?;
    if (grey != null) {
      buffer.writeln();
      buffer.writeln('  // Grey palette');
      grey.forEach((shade, config) {
        if (shade.startsWith('\$')) return;
        if (config is Map && config.containsKey('\$value')) {
          final hex = config['\$value'] as String;
          buffer.writeln('  static const Color grey$shade = ${_hexToColor(hex)};');
        }
      });
    }
  }

  buffer.writeln('}');
  return buffer.toString();
}

/// Generate semantic color tokens
String _generateSemanticColorTokens(
  Map<String, dynamic> colorSemantic,
  Map<String, dynamic> primitives,
) {
  final buffer = StringBuffer();
  buffer.writeln('/// Semantic color tokens.');
  buffer.writeln('/// Purpose-driven colors for UI elements.');
  buffer.writeln('/// PLACEHOLDER values - customize for unique brand identity.');
  buffer.writeln('class SemanticColorTokens {');
  buffer.writeln('  const SemanticColorTokens();');
  buffer.writeln();

  // Brand colors
  final brand = colorSemantic['brand'] as Map<String, dynamic>?;
  if (brand != null) {
    buffer.writeln('  // Brand identity colors');
    brand.forEach((name, config) {
      if (name.startsWith('\$')) return;
      if (config is Map && config.containsKey('\$value')) {
        final resolved = _resolveReference(config['\$value'], primitives);
        final desc = config['\$description'] as String?;

        if (desc != null) buffer.writeln('  /// $desc');
        buffer.writeln('  static const Color $name = ${_hexToColor(resolved)};');
      }
    });
    buffer.writeln();
  }

  // Surface colors
  final surface = colorSemantic['surface'] as Map<String, dynamic>?;
  if (surface != null) {
    buffer.writeln('  // Surface colors');
    surface.forEach((name, config) {
      if (name.startsWith('\$')) return;
      if (config is Map && config.containsKey('\$value')) {
        final resolved = _resolveReference(config['\$value'], primitives);
        final desc = config['\$description'] as String?;
        final propName = 'surface${_capitalize(name)}';

        if (desc != null) buffer.writeln('  /// $desc');
        buffer.writeln('  static const Color $propName = ${_hexToColor(resolved)};');
      }
    });
    buffer.writeln();
  }

  // Feedback colors
  final feedback = colorSemantic['feedback'] as Map<String, dynamic>?;
  if (feedback != null) {
    buffer.writeln('  // Feedback colors');
    feedback.forEach((name, config) {
      if (name.startsWith('\$')) return;
      if (config is Map && config.containsKey('\$value')) {
        final hex = config['\$value'] as String;
        buffer.writeln('  static const Color $name = ${_hexToColor(hex)};');
      }
    });
  }

  buffer.writeln('}');
  return buffer.toString();
}

/// Generate component tokens
String _generateComponentTokens(
  Map<String, dynamic> component,
  Map<String, dynamic> primitives,
) {
  final buffer = StringBuffer();
  buffer.writeln('/// Component-specific tokens.');
  buffer.writeln('/// PLACEHOLDER structure - expand as widgets are designed.');
  buffer.writeln('class ComponentTokens {');
  buffer.writeln('  const ComponentTokens();');

  // Button
  final button = component['button'] as Map<String, dynamic>?;
  if (button != null) {
    buffer.writeln();
    buffer.writeln('  // Button');
    final padding = button['padding'] as Map<String, dynamic>?;
    final hPad = _resolveSpacing(padding?['horizontal']?['\$value'], primitives);
    final vPad = _resolveSpacing(padding?['vertical']?['\$value'], primitives);
    final radius = _resolveBorderRadius(button['borderRadius']?['\$value'], primitives);
    final minHeight = _parseValue(button['minHeight']?['\$value'] ?? '48px');

    buffer.writeln('  static const EdgeInsets buttonPadding = EdgeInsets.symmetric(');
    buffer.writeln('    horizontal: $hPad,');
    buffer.writeln('    vertical: $vPad,');
    buffer.writeln('  );');
    buffer.writeln('  static const double buttonBorderRadius = $radius;');
    buffer.writeln('  static const double buttonMinHeight = $minHeight;');
  }

  // Card
  final card = component['card'] as Map<String, dynamic>?;
  if (card != null) {
    buffer.writeln();
    buffer.writeln('  // Card');
    final padding = _resolveSpacing(card['padding']?['\$value'], primitives);
    final radius = _resolveBorderRadius(card['borderRadius']?['\$value'], primitives);
    final elevationRaw = card['elevation']?['\$value'];
    final elevation = elevationRaw is num
        ? elevationRaw.toDouble()
        : (double.tryParse(elevationRaw?.toString() ?? '') ?? 1.0);

    buffer.writeln('  static const double cardPadding = $padding;');
    buffer.writeln('  static const double cardBorderRadius = $radius;');
    buffer.writeln('  static const double cardElevation = $elevation;');
  }

  // Input
  final input = component['input'] as Map<String, dynamic>?;
  if (input != null) {
    buffer.writeln();
    buffer.writeln('  // Input');
    final padding = input['padding'] as Map<String, dynamic>?;
    final hPad = _resolveSpacing(padding?['horizontal']?['\$value'], primitives);
    final vPad = _resolveSpacing(padding?['vertical']?['\$value'], primitives);
    final radius = _resolveBorderRadius(input['borderRadius']?['\$value'], primitives);
    final minHeight = _parseValue(input['minHeight']?['\$value'] ?? '56px');

    buffer.writeln('  static const EdgeInsets inputPadding = EdgeInsets.symmetric(');
    buffer.writeln('    horizontal: $hPad,');
    buffer.writeln('    vertical: $vPad,');
    buffer.writeln('  );');
    buffer.writeln('  static const double inputBorderRadius = $radius;');
    buffer.writeln('  static const double inputMinHeight = $minHeight;');
  }

  buffer.writeln('}');
  return buffer.toString();
}

/// Generate BuildContext extension
String _generateContextExtension(bool hasSemantic, bool hasComponent) {
  final buffer = StringBuffer();
  buffer.writeln('/// Extension for convenient token access via BuildContext.');
  buffer.writeln('extension TokensExtension on BuildContext {');
  buffer.writeln('  SpacingTokens get spacingTokens => const SpacingTokens();');
  buffer.writeln('  BorderRadiusTokens get borderRadiusTokens => const BorderRadiusTokens();');
  buffer.writeln('  FontSizeTokens get fontSizeTokens => const FontSizeTokens();');
  buffer.writeln('  ColorTokens get colorTokens => const ColorTokens();');
  if (hasSemantic) {
    buffer.writeln('  SemanticColorTokens get semanticColorTokens => const SemanticColorTokens();');
  }
  if (hasComponent) {
    buffer.writeln('  ComponentTokens get componentTokens => const ComponentTokens();');
  }
  buffer.writeln('}');
  return buffer.toString();
}

/// Generate animation_tokens.g.dart file
String _generateAnimationTokensFile(
  Map<String, dynamic> primitives,
  Map<String, dynamic> theme,
) {
  // Extract primitive durations
  final durations = <String, int>{};
  final duration = primitives['duration'] as Map<String, dynamic>?;
  if (duration != null) {
    duration.forEach((name, config) {
      if (name.startsWith('\$')) return;
      if (config is Map && config.containsKey('\$value')) {
        durations[name] = _parseDuration(config['\$value']);
      }
    });
  }

  int resolveDuration(String? ref) {
    if (ref == null) return 0;
    final match = RegExp(r'\{primitives\.duration\.(\w+)\}').firstMatch(ref);
    if (match != null) {
      return durations[match.group(1)] ?? 0;
    }
    return _parseDuration(ref);
  }

  // Extract tree theme animations
  final tree = theme['tree']?['animation'] as Map<String, dynamic>?;
  final treeEntrance = resolveDuration(tree?['entrance']?['\$value']);
  final treeExit = resolveDuration(tree?['exit']?['\$value']);
  final treeFeedback = resolveDuration(tree?['feedback']?['\$value']);
  final treeIdle = resolveDuration(tree?['idle']?['\$value']);

  // Extract simple theme animations
  final simple = theme['simple']?['animation'] as Map<String, dynamic>?;
  final simpleEntrance = resolveDuration(simple?['entrance']?['\$value']);
  final simpleExit = resolveDuration(simple?['exit']?['\$value']);
  final simpleFeedback = resolveDuration(simple?['feedback']?['\$value']);
  final simpleIdle = resolveDuration(simple?['idle']?['\$value']);

  return '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: dart run scripts/process_design_tokens.dart
// Source: lib/config/theme/tokens.json (W3C DTCG format)

// ignore_for_file: public_member_api_docs

/// Animation token interface.
/// Why: Provides a common interface for TreeTheme and SimpleTheme
/// animation durations, enabling polymorphic access in widgets.
abstract class AnimationTokens {
  const AnimationTokens();

  Duration get entrance;
  Duration get exit;
  Duration get feedback;
  Duration get idle;
}

/// Tree Theme animation tokens.
/// Organic, growth-like animations for the full Tree Theme experience.
class TreeThemeAnimationTokens extends AnimationTokens {
  const TreeThemeAnimationTokens();

  @override
  Duration get entrance => const Duration(milliseconds: $treeEntrance);

  @override
  Duration get exit => const Duration(milliseconds: $treeExit);

  @override
  Duration get feedback => const Duration(milliseconds: $treeFeedback);

  @override
  Duration get idle => const Duration(milliseconds: $treeIdle);
}

/// Simple Theme animation tokens.
/// Fast, minimal animations for reduced motion preference.
class SimpleThemeAnimationTokens extends AnimationTokens {
  const SimpleThemeAnimationTokens();

  @override
  Duration get entrance => const Duration(milliseconds: $simpleEntrance);

  @override
  Duration get exit => const Duration(milliseconds: $simpleExit);

  @override
  Duration get feedback => const Duration(milliseconds: $simpleFeedback);

  @override
  Duration get idle => const Duration(milliseconds: $simpleIdle);
}
''';
}

// === Helper functions ===

/// Parse numeric value from W3C format (handles "8px", "16", etc.)
double _parseValue(dynamic value) {
  if (value == null) return 0.0;
  if (value is num) return value.toDouble();
  if (value is String) {
    final numStr = value.replaceAll(RegExp(r'[a-zA-Z%]+'), '');
    return double.tryParse(numStr) ?? 0.0;
  }
  return 0.0;
}

/// Parse duration from W3C format (handles "800ms", "0ms", etc.)
int _parseDuration(dynamic value) {
  if (value == null) return 0;
  if (value is num) return value.toInt();
  if (value is String) {
    final numStr = value.replaceAll(RegExp(r'[a-zA-Z]+'), '');
    return int.tryParse(numStr) ?? 0;
  }
  return 0;
}

/// Resolve token reference like {primitives.color.brand.green.500}
String _resolveReference(String? ref, Map<String, dynamic> primitives) {
  if (ref == null || !ref.startsWith('{')) return ref ?? '';

  final path = ref.substring(1, ref.length - 1).split('.');
  if (path.isEmpty || path[0] != 'primitives') return ref;

  dynamic current = primitives;
  for (var i = 1; i < path.length; i++) {
    if (current is Map && current.containsKey(path[i])) {
      current = current[path[i]];
    } else {
      return ref; // Could not resolve
    }
  }

  if (current is Map && current.containsKey('\$value')) {
    return current['\$value'] as String;
  }
  return ref;
}

/// Resolve spacing reference
double _resolveSpacing(String? ref, Map<String, dynamic> primitives) {
  if (ref == null) return 16.0;
  if (!ref.startsWith('{')) return _parseValue(ref);

  final match = RegExp(r'\{primitives\.spacing\.scale\.(\w+)\}').firstMatch(ref);
  if (match != null) {
    final scaleName = match.group(1)!;
    final spacing = primitives['spacing'] as Map<String, dynamic>?;
    final base = _parseValue(spacing?['base']?['\$value']);
    final scale = spacing?['scale'] as Map<String, dynamic>?;
    final factor = (scale?[scaleName]?['\$value'] as num?)?.toDouble() ?? 1.0;
    return base * factor;
  }

  return _parseValue(ref);
}

/// Resolve border radius reference
double _resolveBorderRadius(String? ref, Map<String, dynamic> primitives) {
  if (ref == null) return 8.0;
  if (!ref.startsWith('{')) return _parseValue(ref);

  final match = RegExp(r'\{primitives\.borderRadius\.(\w+)\}').firstMatch(ref);
  if (match != null) {
    final name = match.group(1)!;
    final br = primitives['borderRadius'] as Map<String, dynamic>?;
    return _parseValue(br?[name]?['\$value']);
  }

  return _parseValue(ref);
}

/// Convert hex color to Flutter Color
String _hexToColor(String hex) {
  final cleanHex = hex.replaceAll('#', '');
  if (cleanHex.length == 6) {
    return 'Color(0xFF${cleanHex.toUpperCase()})';
  } else if (cleanHex.length == 8) {
    return 'Color(0x${cleanHex.toUpperCase()})';
  }
  return 'Color(0xFF000000)';
}

/// Capitalize first letter
String _capitalize(String s) {
  if (s.isEmpty) return s;
  return s[0].toUpperCase() + s.substring(1);
}

/// Sanitize name for Dart identifier (handle names like "2xl")
String _sanitizeName(String name) {
  if (RegExp(r'^[0-9]').hasMatch(name)) {
    final match = RegExp(r'^(\d+)(\w+)').firstMatch(name);
    if (match != null) {
      final num = int.tryParse(match.group(1)!) ?? 2;
      final suffix = match.group(2)!;
      return '${'x' * num}$suffix';
    }
    return 'size$name';
  }
  return name;
}
