#!/usr/bin/env python3
"""Regression tests for scripts/artifacts/merge_requirements.py.

Pins the faithful-port behaviour of the directory-tree builder, the markdown
collector (tasks-folder exclusion + category filter), and the no-BOM/LF
output writer against the original merge_requirements.ps1 semantics.
"""

from pathlib import Path

from scripts.artifacts import merge_requirements as m


def _touch(path: Path, content: str = "x") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


# ---------------------------------------------------------------------------
# get_directory_tree — connectors, sort order, tasks-folder handling
# ---------------------------------------------------------------------------


def test_tree_connectors_and_dir_before_file_sort(tmp_path: Path) -> None:
    # zfolder sorts after afile by name, but directories come first regardless.
    (tmp_path / "zdir").mkdir()
    _touch(tmp_path / "zdir" / "inner.md")
    _touch(tmp_path / "afile.md")
    _touch(tmp_path / "bfile.md")

    tree = m.get_directory_tree(tmp_path)

    assert tree == [
        "|-- zdir",
        "|   +-- inner.md",
        "|-- afile.md",
        "+-- bfile.md",
    ]


def test_tree_tasks_folder_shows_children_but_not_contents(
    tmp_path: Path,
) -> None:
    tasks = tmp_path / "tasks"
    tasks.mkdir()
    # Each task folder has nested content that must NOT be descended into.
    _touch(tasks / "2026-01-01_explore_foo" / "goal.md")
    _touch(tasks / "2026-02-02_impl_bar (completed)" / "goal.md")

    tree = m.get_directory_tree(tmp_path)

    assert tree == [
        "+-- tasks",
        "    |-- 2026-01-01_explore_foo",
        "    +-- 2026-02-02_impl_bar (completed)",
    ]


def test_tree_nested_tasks_inside_feature(tmp_path: Path) -> None:
    feat = tmp_path / "feat_x"
    feat.mkdir()
    _touch(feat / "requirements.md")
    tasks = feat / "tasks"
    tasks.mkdir()
    _touch(tasks / "t1" / "goal.md")

    tree = m.get_directory_tree(tmp_path)

    assert tree == [
        "+-- feat_x",
        "    |-- tasks",
        "    |   +-- t1",
        "    +-- requirements.md",
    ]


# ---------------------------------------------------------------------------
# get_markdown_files — tasks exclusion, category filter, path sort
# ---------------------------------------------------------------------------


def test_markdown_excludes_files_inside_tasks_folder(tmp_path: Path) -> None:
    _touch(tmp_path / "requirements.md")
    _touch(tmp_path / "tasks" / "t1" / "goal.md")
    _touch(tmp_path / "sub" / "feature.md")

    files = m.get_markdown_files(tmp_path)
    rels = sorted(f.relative_to(tmp_path).as_posix() for f in files)

    assert rels == ["requirements.md", "sub/feature.md"]


def test_markdown_category_filter_only_in_requirements_tasks(
    tmp_path: Path,
) -> None:
    base = tmp_path / "requirements_tasks"
    _touch(base / "functional" / "a.md")
    _touch(base / "process" / "b.md")
    _touch(base / "top.md")

    files = m.get_markdown_files(base, category_filter="functional")
    rels = sorted(f.relative_to(base).as_posix() for f in files)

    # top.md is not under requirements_tasks/functional/ -> filtered out.
    assert rels == ["functional/a.md"]


def test_markdown_missing_folder_returns_empty(tmp_path: Path) -> None:
    assert m.get_markdown_files(tmp_path / "does_not_exist") == []


# ---------------------------------------------------------------------------
# output writer — no BOM, LF endings (verified via build_content join)
# ---------------------------------------------------------------------------


def test_build_content_header_references_new_python_path() -> None:
    content = m.build_content(category=None)
    joined = "\n".join(content)
    assert (
        "automatically generated by "
        "`scripts/artifacts/merge_requirements.py`" in joined
    )
    assert "\r" not in joined


def test_build_content_category_filter_banner() -> None:
    content = m.build_content(category="functional")
    joined = "\n".join(content)
    assert "> **Filter Active:** Only showing **functional** requirements" in joined
    assert "> **Category Filter:** functional" in joined
